import { Products } from "./index";
// products of Bvg network, generated by a tool
export interface ProductsBvg extends Products {
    "bus": boolean;
    "express": boolean;
    "ferry": boolean;
    "regional": boolean;
    "suburban": boolean;
    "subway": boolean;
    "tram": boolean;
}
// products of Db network, generated by a tool
export interface ProductsDb extends Products {
    "bus": boolean;
    "ferry": boolean;
    "national": boolean;
    "nationalExpress": boolean;
    "regional": boolean;
    "regionalExp": boolean;
    "suburban": boolean;
    "subway": boolean;
    "taxi": boolean;
    "tram": boolean;
}
// products of Hvv network, generated by a tool
export interface ProductsHvv extends Products {
    "akn": boolean;
    "anruf-sammel-taxi": boolean;
    "bus": boolean;
    "express-bus": boolean;
    "ferry": boolean;
    "long-distance-bus": boolean;
    "long-distance-train": boolean;
    "regional-express-train": boolean;
    "regional-train": boolean;
    "suburban": boolean;
    "subway": boolean;
}
// products of Insa network, generated by a tool
export interface ProductsInsa extends Products {
    "bus": boolean;
    "national": boolean;
    "nationalExpress": boolean;
    "regional": boolean;
    "suburban": boolean;
    "tourismTrain": boolean;
    "tram": boolean;
}
// products of Nahsh network, generated by a tool
export interface ProductsNahsh extends Products {
    "bus": boolean;
    "ferry": boolean;
    "interregional": boolean;
    "national": boolean;
    "nationalExpress": boolean;
    "onCall": boolean;
    "regional": boolean;
    "suburban": boolean;
    "subway": boolean;
    "tram": boolean;
}
// products of Oebb network, generated by a tool
export interface ProductsOebb extends Products {
    "bus": boolean;
    "ferry": boolean;
    "interregional": boolean;
    "national": boolean;
    "nationalExpress": boolean;
    "onCall": boolean;
    "regional": boolean;
    "suburban": boolean;
    "subway": boolean;
    "tram": boolean;
}
// products of Pkp network, generated by a tool
export interface ProductsPkp extends Products {
    "bus": boolean;
    "high-speed-train": boolean;
    "long-distance-train": boolean;
    "regional-train": boolean;
}
// products of Rsag network, generated by a tool
export interface ProductsRsag extends Products {
    "bus": boolean;
    "ferry": boolean;
    "ic-ec": boolean;
    "ice": boolean;
    "long-distance-train": boolean;
    "on-call": boolean;
    "regional-train": boolean;
    "s-bahn": boolean;
    "tram": boolean;
    "u-bahn": boolean;
}
// products of SBahnMunich network, generated by a tool
export interface ProductsSBahnMunich extends Products {
    "bus": boolean;
    "ic-ec": boolean;
    "ice": boolean;
    "ir-d": boolean;
    "on-call": boolean;
    "region": boolean;
    "sbahn": boolean;
    "tram": boolean;
    "ubahn": boolean;
}
