#!/bin/bash
# generate a ts declaration file for every profile in 'hafas-client/p'

RmDirs="yes"
NODEDIR="./node_modules/hafas-client/p"
for filename in $(ls ${NODEDIR}); do
    if [ -f ${NODEDIR}/$filename/index.js ]; then 
        DIRECTORY="./types/hafas-client/p/$filename"
        if [ -d "$DIRECTORY" ] && [ ${RmDirs} == "yes" ]; then
            echo "rmdir $DIRECTORY"
            rm -rf "$DIRECTORY"
        fi
        if [ ! -d "$DIRECTORY" ]; then
            echo $DIRECTORY

            mkdir $DIRECTORY
            PROFILE=$(echo ${filename} | sed 's/-//g')
            PROFILE="${PROFILE}Profile"
            FILE="$DIRECTORY/index.d.ts"
            cat > $FILE <<- EOM
export = ${PROFILE};

import createClient = require('../../index');

declare const ${PROFILE}: createClient.Profile;
EOM
        fi
    fi
done