#!/bin/bash

./scripts/getproducttype Bvg
./scripts/getproducttype Db
./scripts/getproducttype Hvv
./scripts/getproducttype Insa
./scripts/getproducttype Nahsh
./scripts/getproducttype Oebb
./scripts/getproducttype Pkp
./scripts/getproducttype Rsag
./scripts/getproducttype SBahnMunich
./scripts/getproducttype Sncb