#!/bin/bash

./scripts/runtest Bvg check-locations Alexanderplatz
./scripts/runtest Cfl check-locations Luxembourg
./scripts/runtest Cmta check-locations King
./scripts/runtest Db check-locations Hannover
./scripts/runtest DbBusradarNrw check-locations Essen
./scripts/runtest Hvv check-locations Dammtor
./scripts/runtest Insa check-locations Magdeburg
./scripts/runtest Invg check-locations Ingolstadt
./scripts/runtest Nahsh check-locations Husum
./scripts/runtest Nvv check-locations Nidda
./scripts/runtest Oebb check-locations Wien
./scripts/runtest Pkp check-locations Warschau
./scripts/runtest Rmv check-locations Mainz
./scripts/runtest Rsag check-locations Warnemünde 
./scripts/runtest Saarfahrplan check-locations Trier
./scripts/runtest SBahnMunich check-locations Harras
 ./scripts/runtest Sncb check-locations Antwerpen
./scripts/runtest Vbb check-locations Alexanderplatz
./scripts/runtest Vbn check-locations Thale
./scripts/runtest Vmt check-locations Suhl
./scripts/runtest Vsn check-locations Seesen

./scripts/runtest Db check-departures 8000152

./scripts/runtest Db check-reachableFrom Hannover

./scripts/runtest Bvg check-journeys Alexanderplatz OsloerStr
./scripts/runtest Db check-journeys Berlin Paris
./scripts/runtest Db check-journeys Berlin London
./scripts/runtest Db check-journeys Berlin Moskau
./scripts/runtest Nahsh check-journeys Husum Flenburg
./scripts/runtest Oebb check-journeys Berlin Wien
./scripts/runtest Pkp check-journeys Berlin Warschau
./scripts/runtest Sncb check-journeys Antwerpen Brüssel