#!/bin/bash

./scripts/runtest Bvg locations Alexanderplatz
./scripts/runtest Db locations Hannover
./scripts/runtest Nahsh locations Husum
./scripts/runtest Oebb locations Wien
./scripts/runtest Pkp locations Warschau
./scripts/runtest Vbb locations Alexanderplatz

./scripts/runtest Db reachableFrom Hannover

./scripts/runtest Bvg journeys Alexanderplatz OsloerStr
./scripts/runtest Db journeys Berlin Paris
./scripts/runtest Db journeys Berlin London
./scripts/runtest Db journeys Berlin Moskau
./scripts/runtest Nahsh journeys Husum Flenburg
./scripts/runtest Oebb journeys Berlin Wien
./scripts/runtest Pkp journeys Berlin Warschau
./scripts/runtest Sncb journeys Hannover Brüssel