#!/bin/bash

# the files xx01*.json should be a superset of the corresponding files xx00*.json 
# check it in 4 steps
# 1) sort with jq
# 2) remove null values
# 3) repair json
# 4) compare files with diff

check_files () {
    local NAME=$1
    jq -S '.' xx00${NAME}.json > xx00${NAME}-s.json
    sed  '/: null/d' xx00${NAME}-s.json > xx00${NAME}-d.json
    jq -S '.' xx01${NAME}.json > xx01${NAME}-s.json
    sed  '/: null/d' xx01${NAME}-s.json > xx01${NAME}-d.json

    # change ',\n}' to '\n}'
    sed -E -e ':a;N;$!ba;s/,\n([[:blank:]]+)\x7d/\n\1\x7d/g' xx00${NAME}-d.json > xx00${NAME}-x.json
    sed -E -e ':a;N;$!ba;s/,\n([[:blank:]]+)\x7d/\n\1\x7d/g' xx01${NAME}-d.json > xx01${NAME}-x.json

    diff -I ": null" xx00${NAME}-x.json xx01${NAME}-x.json
}

if [ $# -lt 3 ]
then
    echo "3 or more args needed"
    exit 1
fi

PROFILE=$1
CMD=$2
X=$3

if [ $# -eq 3 ]
then
    NAME=${PROFILE}-${CMD}-${X}
    NAME=$(echo $NAME | sed 's/ //g')
    rm -f xx*${NAME}*.json
    rm -f ./out/xx*${NAME}*.json
    echo "${PROFILE} ${CMD} ${X}"
    node ./build/JourneyInfoApp.js ${PROFILE} ${CMD} ${X} | csplit -sb "%02d${NAME}.json" - 2
    check_files $NAME && echo "Success"
    mv xx*.json ./out
fi

if [ $# -eq 4 ]
then
    Y=$4
    NAME=${PROFILE}-${CMD}-${X}-${Y}
    NAME=$(echo $NAME | sed 's/ //g')
    rm -f xx*${NAME}*.json
    rm -f ./out/xx*${NAME}*.json
    echo "${PROFILE} ${CMD} ${X} ${Y}"
    node ./build/JourneyInfoApp.js ${PROFILE} ${CMD} ${X} ${Y} | csplit -sb "%02d${NAME}.json" - 2
    check_files $NAME && echo "Success"
    mv xx*.json ./out
fi

